GRANT CREATE VIEW TO ASlizh;
GRANT CREATE ANY TABLE TO ASlizh;
GRANT CREATE MATERIALIZED VIEW TO ASlizh;
GRANT CREATE DATABASE LINK TO ASlizh;
GRANT GLOBAL QUERY REWRITE TO ASlizh;
GRANT ON COMMIT REFRESH TO ASlizh;