--===========================================
-- RANG PARTITIONING
--===========================================

-- Table SALES
CREATE TABLE SALES
(
    sale_id NUMBER(10),
    time_id DATE,
    product_id NUMBER(10),
    amount NUMBER(10)
)
PARTITION BY RANGE (time_id)
(
    PARTITION SALES_2021 VALUES LESS THAN (TO_DATE('01/01/2022', 'DD/MM/YYYY')),
    PARTITION SALES_2022 VALUES LESS THAN (TO_DATE('01/01/2023', 'DD/MM/YYYY'))
)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

INSERT INTO SALES VALUES(1, TO_DATE('10/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(2, TO_DATE('11/01/2021', 'DD/MM/YYYY'), 2, 1);
INSERT INTO SALES VALUES(3, TO_DATE('10/01/2022', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(4, TO_DATE('11/01/2022', 'DD/MM/YYYY'), 2, 1);
commit;

-- Merge partitions
ALTER TABLE SALES
MERGE PARTITIONS SALES_2021, SALES_2022
INTO PARTITION SALES_2021_2022;

-- Move partitions
ALTER TABLE SALES
MOVE PARTITION SALES_2021_2022
TABLESPACE TS_REFERENCES_DATA_01 NOLOGGING COMPRESS;

-- Split partition
ALTER TABLE SALES SPLIT PARTITION SALES_2021_2022
AT (TO_DATE('01/01/2022', 'DD/MM/YYYY'))
INTO (PARTITION SALES_2021, PARTITION SALES_2022);

-- Truncate partition SALES_2021
ALTER TABLE SALES TRUNCATE PARTITION SALES_2021;

-- Drop partition SALES_2021
ALTER TABLE SALES DROP PARTITION SALES_2021;

-- Add partition SALES_2023
ALTER TABLE SALES
ADD PARTITION SALES_2023 VALUES LESS THAN (TO_DATE('01/01/2024', 'DD/MM/YYYY'))
TABLESPACE TS_REFERENCES_EXT_DATA_01;

-- Clear table
DROP TABLE SALES;
PURGE RECYCLEBIN;

--===========================================
-- INERVAL PARTITIONING
--===========================================

-- Table SALES
CREATE TABLE SALES
(
    sale_id NUMBER(10),
    time_id DATE,
    product_id NUMBER(10),
    amount NUMBER(10)
)
PARTITION BY RANGE (time_id)
INTERVAL(NUMTOYMINTERVAL(1,'MONTH'))
(
    PARTITION SALES_2021 VALUES LESS THAN (TO_DATE('01/01/2022', 'DD/MM/YYYY')) TABLESPACE TS_REFERENCES_EXT_DATA_01,
    PARTITION SALES_2022 VALUES LESS THAN (TO_DATE('01/01/2023', 'DD/MM/YYYY')) TABLESPACE TS_REFERENCES_DATA_01
);

INSERT INTO SALES VALUES(1, TO_DATE('10/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(2, TO_DATE('11/01/2021', 'DD/MM/YYYY'), 2, 1);
INSERT INTO SALES VALUES(3, TO_DATE('10/01/2022', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(4, TO_DATE('11/01/2022', 'DD/MM/YYYY'), 2, 1);
commit;

-- Merge partitions
ALTER TABLE SALES
MERGE PARTITIONS SALES_2021, SALES_2022
INTO PARTITION SALES_2021_2022;

-- Move partitions
ALTER TABLE SALES
MOVE PARTITION SALES_2021_2022
TABLESPACE TS_REFERENCES_DATA_01 NOLOGGING COMPRESS;

-- Split partition
ALTER TABLE SALES SPLIT PARTITION SALES_2021_2022
AT (TO_DATE('01/01/2022', 'DD/MM/YYYY'))
INTO (PARTITION SALES_2021, PARTITION SALES_2022);

-- Truncate partition SALES_2021
ALTER TABLE SALES TRUNCATE PARTITION SALES_2021;

-- Drop partition SALES_2021
ALTER TABLE SALES DROP PARTITION SALES_2021;

-- Clear table
DROP TABLE SALES;
PURGE RECYCLEBIN;

--===========================================
-- LIST PARTITIONING
--===========================================

-- Table SALES
CREATE TABLE SALES
(
    sale_id NUMBER(10),
    time_id DATE,
    product_id NUMBER(10),
    amount NUMBER(10)
)
PARTITION BY LIST (product_id)
(
    PARTITION PROD_1 VALUES(1),
    PARTITION PROD_2 VALUES(2)
)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

INSERT INTO SALES VALUES(1, TO_DATE('10/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(2, TO_DATE('11/01/2021', 'DD/MM/YYYY'), 2, 1);
INSERT INTO SALES VALUES(3, TO_DATE('10/01/2022', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(4, TO_DATE('11/01/2022', 'DD/MM/YYYY'), 2, 1);
commit;

-- Merge partitions
ALTER TABLE SALES
MERGE PARTITIONS PROD_1, PROD_2
INTO PARTITION PROD_1_2;

-- Move partitions
ALTER TABLE SALES
MOVE PARTITION PROD_1_2
TABLESPACE TS_REFERENCES_DATA_01 NOLOGGING COMPRESS;

-- Split partition
ALTER TABLE SALES SPLIT PARTITION PROD_1_2
VALUES(1)
INTO(PARTITION PROD_1, PARTITION PROD_2);

-- Truncate partition PROD_1
ALTER TABLE SALES TRUNCATE PARTITION PROD_1;

-- Drop partition PROD_1
ALTER TABLE SALES DROP PARTITION PROD_1;

-- Add new partition PROD_3
ALTER TABLE SALES 
ADD PARTITION PROD_3 VALUES (3)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

-- Clear table
DROP TABLE SALES;
PURGE RECYCLEBIN;

--===========================================
-- HASH PARTITIONING
--===========================================

-- Create table SALES
CREATE TABLE SALES
(
    sale_id NUMBER(10),
    time_id DATE,
    product_id NUMBER(10),
    amount NUMBER(10)
)
PARTITION BY HASH (product_id)
(
    PARTITION P1 TABLESPACE TS_REFERENCES_DATA_01,
    PARTITION P2 TABLESPACE TS_REFERENCES_EXT_DATA_01
);

INSERT INTO SALES VALUES(1, TO_DATE('10/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(2, TO_DATE('11/01/2021', 'DD/MM/YYYY'), 2, 1);
INSERT INTO SALES VALUES(3, TO_DATE('10/01/2022', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(4, TO_DATE('11/01/2022', 'DD/MM/YYYY'), 3, 1);
INSERT INTO SALES VALUES(3, TO_DATE('12/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(4, TO_DATE('12/01/2022', 'DD/MM/YYYY'), 3, 1);
commit;

-- Add new partition
ALTER TABLE SALES 
ADD PARTITION P3
TABLESPACE TS_REFERENCES_EXT_DATA_01;

-- Truncate partition P1
ALTER TABLE SALES TRUNCATE PARTITION P1;

-- Coalesce partition
ALTER TABLE SALES
COALESCE PARTITION;

-- Clear table
DROP TABLE SALES;
PURGE RECYCLEBIN;

--===========================================
-- REFERENCE PARTITIONING
--===========================================

-- Creating tables
CREATE TABLE PRODUCTS
(
    product_id NUMBER NOT NULL,
    name VARCHAR2(50) NOT NULL,
    CONSTRAINT product_pk PRIMARY KEY(product_id)
)
PARTITION BY RANGE (product_id)
(
PARTITION P1 VALUES LESS THAN (10),
PARTITION P2 VALUES LESS THAN (20)
)

CREATE TABLE SALES
(
    sale_id NUMBER(10) NOT NULL,
    time_id DATE NOT NULL,
    product_id NUMBER(10) NOT NULL,
    amount NUMBER(10) NOT NULL,
    CONSTRAINT product_id_fk FOREIGN KEY(product_id) REFERENCES PRODUCTS(product_id)
)
PARTITION BY REFERENCE(product_id_fk);

INSERT INTO PRODUCTS VALUES(1, 'Banka PEPSI');
INSERT INTO PRODUCTS VALUES(2, 'Cheetos');
INSERT INTO PRODUCTS VALUES(11, 'Syrok s pandoy');
INSERT INTO PRODUCTS VALUES(12, 'Girchitsa');
INSERT INTO SALES VALUES(1, TO_DATE('10/01/2021', 'DD/MM/YYYY'), 1, 1);
INSERT INTO SALES VALUES(2, TO_DATE('11/01/2021', 'DD/MM/YYYY'), 2, 1);
INSERT INTO SALES VALUES(3, TO_DATE('10/01/2022', 'DD/MM/YYYY'), 11, 1);
INSERT INTO SALES VALUES(4, TO_DATE('11/01/2022', 'DD/MM/YYYY'), 12, 1);
COMMIT;

-- Move partitions
ALTER TABLE SALES
MOVE PARTITION P1
TABLESPACE TS_REFERENCES_DATA_01 NOLOGGING COMPRESS;

-- Truncate partition P1
ALTER TABLE SALES TRUNCATE PARTITION P1;

-- Clear table
DROP TABLE SALES;
DROP TABLE PRODUCTS;
PURGE RECYCLEBIN;